Implements Undo command
AY2425S1-CS2103T-T14-4/tp pull request #147
Opened 2024-10-27 14:38 UTC by FionaQY

Closes https://github.com/AY2425S1-CS2103T-T14-4/tp/issues/146

2024-10-30 10:58 UTC, colinhia approved these changes
Overall LGTM! Just caught a minor typo in safeHistory

2024-10-30 10:58 UTC, colinhia commented on src/main/java/seedu/address/model/ModelManager.java
> +    private void safeHistory() {
I think this might be a minor typo? saveHistory

2024-10-30 10:58 UTC, colinhia commented on src/main/java/seedu/address/model/ModelManager.java
>      }
Great use of abstraction! Liked how clean this is with just adding saveHistory into each command works.

2024-10-30 11:45 UTC, itsme-zeix requested changes
Overall LGTM! Just some small changes to be made.

2024-10-30 11:45 UTC, itsme-zeix commented on src/main/java/seedu/address/model/ModelManager.java
> +    private void safeHistory() {
```suggestion
    private void saveHistory() {
```

2024-10-30 11:45 UTC, itsme-zeix commented on src/main/java/seedu/address/model/ModelManager.java
> +        safeHistory();
```suggestion
        saveHistory();
```

2024-10-30 11:45 UTC, itsme-zeix commented on src/main/java/seedu/address/model/ModelManager.java
> +        safeHistory();
```suggestion
        saveHistory();
```

2024-10-30 11:45 UTC, itsme-zeix commented on src/main/java/seedu/address/model/ModelManager.java
> +        safeHistory();
```suggestion
        saveHistory();
```

2024-10-30 11:45 UTC, itsme-zeix commented on src/main/java/seedu/address/model/ModelManager.java
> +        safeHistory();
```suggestion
        saveHistory();
```

2024-10-30 11:45 UTC, itsme-zeix commented on src/main/java/seedu/address/logic/commands/UndoCommand.java
> + */
Needs to be updated!

2024-11-01 06:28 UTC, itsme-zeix approved these changes
LGTM! Thanks for making the changes!

2024-11-01 06:31 UTC, merged