Update DG
AY2425S1-CS2103T-T14-4/tp pull request #342
Opened 2024-11-11 17:30 UTC by FionaQY

2024-11-11 17:31 UTC, iamdiluxedbutcooler requested changes
LGTM! just a minor change :D

2024-11-11 17:31 UTC, iamdiluxedbutcooler commented on docs/DeveloperGuide.md
> +    3. Test case: `add n/ <NAME> p/ <PHONE> e/ <EMAIL> a/ <ADDRESS> j/ <JOB> i/ <INCOME> t/ <TIER> r/ <REMARK> s/ <Status>`<br>
Status should be STATUS?

2024-11-12 03:30 UTC, itsme-zeix approved these changes
LGTM

2024-11-12 03:37 UTC, ZShunRen approved these changes
LGTM

2024-11-12 04:27 UTC, closed without merging